---
version: "3.1"
services:
  swag:
    image: linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=2001
      - PGID=2001
      - TZ=America/New_York
      - URL=nealslaws.org
      - ONLY_SUBDOMAINS=true
      - SUBDOMAINS=home,neal
      - VALIDATION=http
      - EMAIL=neal.mccorkle@gmail.com
    volumes:
      - /data/docker_config/swag:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    hostname: plex
    environment:
      - PUID=2001
      - PGID=2001
      - TZ=America/New_York
      - VERSION=latest
      - UMASK=022
      - PLEX_CLAIM= #optional; see docker docs
    devices:
      - /dev/dri:/dev/dri # needed for Intel hardware transcode
    ports:
      - 32400:32400
      - 1900:1900/udp
      - 3005:3005
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    volumes:
      - /data/docker_config/plex:/config
      - /data/plex/data:/data
    restart: unless-stopped
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=2001
      - PGID=2001
      - TZ=America/New_York
    volumes:
      - /data/docker_config/heimdall:/config
    restart: unless-stopped
  ombi:
    image: linuxserver/ombi:v4-preview
    container_name: ombi
    hostname: ombi
    environment:
      - PUID=2001
      - PGID=2001
      - TZ=America/New_York
    volumes:
      - /data/docker_config/ombi:/config
    ports:
      - 3579:3579
    restart: unless-stopped
  tautulli:
    image: ghcr.io/linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=2001
      - PGID=2001
      - TZ=America/New_York
    volumes:
      - /data/docker_config/tautulli:/config
      - /data/docker_config/plex/Library/Application Support/Plex Media Server/Logs:/plex_logs
      - /data/docker_config/tautulli/logs:/logs
    ports:
      - 8181:8181
    restart: unless-stopped
  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=2001
      - PGID=2001
      - TZ=America/New_York
    volumes:
      - /data/docker_config/sabnzbd:/config
      - /data/plex/helper_data:/helper_data
    ports:
      - 8080:8080
      - 9090:9090
    restart: unless-stopped
  nzbhydra2:
    image: ghcr.io/linuxserver/nzbhydra2
    container_name: nzbhydra2
    environment:
      - PUID=2001
      - PGID=2001
      - TZ=America/New_York
    volumes:
      - /data/docker_config/nzbhydra2:/config
    ports:
      - 5076:5076
    restart: unless-stopped
  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=2001
      - PGID=2001
      - TZ=America/New_York
      - UMASK=022
    volumes:
      - /data/docker_config/bazarr:/config
      - /data/plex/data:/data
    ports:
      - 6767:6767
    restart: unless-stopped
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=2001
      - PGID=2001
      - TZ=America/New_York
      - UMASK=022
    volumes:
      - /data/docker_config/sonarr:/config
      - /data/plex/helper_data:/helper_data
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=2001
      - PGID=2001
      - TZ=America/New_York
      - UMASK=022
    volumes:
      - /data/docker_config/radarr:/config
      - /data/plex/helper_data:/helper_data
    ports:
      - 7878:7878
    restart: unless-stopped

